### ISSUE TITLE
Install app is distracting while coding

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#135] opened 2021-10-22 07:48 UTC
### Prerequisites

* [x ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Install app does not have a way to dismiss and its distracting always

### Steps to Reproduce

1. [First Step]
![install_app_is_anoying](https://user-images.githubusercontent.com/1525027/138414829-4cb8a591-678b-467e-a621-1d2e768a4e0c.gif)

2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by abose** [comment] 2022-12-06 16:10
duplicate of https://github.com/phcode-dev/phoenix/issues/143
closing

**Closed by abose** 2022-12-06 16:10 UTC
Labels: enhancement
