### ISSUE TITLE
Drag and drop file to window not working

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#188] opened 2021-10-31 11:19 UTC
1. Phoneix does not open file by drag and drop to window pane ![drag_drop_file_not_Working](https://user-images.githubusercontent.com/1525027/139580432-ff4626a5-36c2-4260-a265-0d5bcadc1ade.gif)
2. Drag and drop files and folder from explorer to phoenix not working

**Comment by abose** [comment] 2022-03-02 08:31
# When the user drops a file or folder, we should provide options to
    1. open the folder as a new project if it is a folder and fs access APIs are supported.
    2. open file to edit directly without adding to project if fs access apis are supported and user dropped a file.
    3. Copy the file/folder to the current project

**Comment by abose** [comment] 2024-06-21 10:52
closing as duplicate of https://github.com/phcode-dev/phoenix/issues/837

**Closed by abose** 2024-06-21 10:52 UTC
Labels: bug
