### ISSUE TITLE
Cannot drag and drop a working file to vertical split

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#821] opened 2023-01-03 11:13 UTC
### Describe the bug

Create a vertical split and drag a file from the working files list.
Ideally, the dragged file should be displayed in a new vertical split.
,

### Reproduction

1. Create a vertical split
2. Drag a working file to vertical split a vertically

### Expected behavior

Dragged file should be displayed in vertical split a 

### OS, Browser and Phoenix versions

Linux
ChromChrome

**Comment by abose** [comment] 2024-01-18 18:38
duplicate of https://github.com/phcode-dev/phoenix/issues/188
closing

**Closed by abose** 2024-01-18 18:38 UTC
Labels: bug
