### ISSUE TITLE
Not running on macOS Big Sur

### ISSUE THREAD

**Issue by Alffrredo** [phcode-dev/phoenix#1867] opened 2024-09-23 11:27 UTC
### Describe the bug

Stuck the app and not running properly

### OS, Browser and Phoenix versions

macOs Big Sur
<img width="1440" alt="Screen Shot 2024-09-23 at 12 25 08 PM" src="https://github.com/user-attachments/assets/965678e5-414c-456b-a53a-42ae7839d372">

**Comment by abose** [comment] 2024-09-23 16:57
Duplicate of https://github.com/phcode-dev/phoenix/issues/1565 .

**Closed** 2024-09-23 16:58 UTC
Labels: bug
