### ISSUE TITLE
[feat]  support for viewing console errors below live preview

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#1178] opened 2023-11-05 15:24 UTC
### Describe the problem

Currently to see the console log we have to popout window and open the console manually

### Describe the solution you'd like

It would prevent a  context switch if I can see the console logs right below the live preview window

**Comment by abose** [comment] 2023-11-07 12:18
Duplicate of https://github.com/phcode-dev/phoenix/issues/704
Closing.

**Closed by abose** 2023-11-07 12:18 UTC
Labels: Feature Request
