### ISSUE TITLE
Persistent install app icon  

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#143] opened 2021-10-22 09:29 UTC
### Steps 
open phoenix web site >click  install app icon
and install the chrome extension 

### Result 
- install app icon remains after the web app extension is installed and opened as a web app

![Screenshot from 2021-10-22 15-25-57](https://user-images.githubusercontent.com/78793827/138434802-e6b887e3-a23b-492d-8992-fc930c43d542.png)

### Expected 
No install app install icon

**Comment by abose** [comment] 2022-12-06 16:10
PWA UX has changed. The issue is no more relevant.
Closing.

**Closed by abose** 2022-12-06 16:10 UTC
Labels: bug
